# Generated by Django 3.2.5 on 2021-07-14 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogueapp', '0004_products_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='author',
            new_name='catelogue',
        ),
    ]
