# Generated by Django 3.2.5 on 2021-08-01 12:35

import catalogueapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogueapp', '0005_rename_author_products_catelogue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catelogues',
            name='thumb',
            field=models.ImageField(blank=True, upload_to=catalogueapp.models.upload_location),
        ),
        migrations.AlterField(
            model_name='products',
            name='thumb',
            field=models.ImageField(blank=True, upload_to=catalogueapp.models.upload_location),
        ),
    ]
